version: '3.7'

services:
  apache:
    build: './DockerApache'
    restart: always
    ports:
      - 6666:80
    networks: 
      - frontend
      - backend
    volumes:
      - ./Data:/usr/local/apache2/htdocs

    depends_on:
      - php
      - mysql
  php:
    build: './DockerPhp'
    restart: always
    networks: 
      - backend
    volumes:
      - ./Data:/usr/local/apache2/htdocs      
  mysql:
    build: './DockerMysql'
    restart: always
    networks:
      - backend
    volumes:
      - ./Database:/var/lib/mysql
networks: 
  backend:
  frontend:
